let
    Source = #date(2017, 6, 1),
    ListDate = List.Dates(Source, Number.From(Date.AddDays(DateTime.LocalNow(),-1))- Number.From(Source) ,#duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(ListDate, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Дата"}}),
    #"Inserted Day of Week" = Table.AddColumn(#"Renamed Columns", "DayOfWeek", each Date.DayOfWeek([Дата]), type number),
    InsertDayName = Table.AddColumn(#"Inserted Day of Week", "День недели", each Date.ToText([Дата], "dddd"), type text),
    #"Inserted Week of Year" = Table.AddColumn(InsertDayName, "Номер недели", each Date.WeekOfYear([Дата]), type number),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Неделя месяца", each Date.WeekOfMonth([Дата]), type number),
    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "StartOfWeek", each Date.StartOfWeek([Дата]), type date),
    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "EndOfWeek", each Date.EndOfWeek([Дата]), type date),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted End of Week", "Quarter", each Date.QuarterOfYear([Дата]), type number),
    #"Inserted Month" = Table.AddColumn(#"Inserted Quarter", "Номер месяца", each Date.Month([Дата]), type number),
    InsertMonthName = Table.AddColumn(#"Inserted Month", "Месяц", each Date.ToText([Дата], "MMMM"), type text),
    #"Inserted Year" = Table.AddColumn(InsertMonthName, "Год", each Date.Year([Дата]), type number),
    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Year", "Год", "Год - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Номер месяца", "Номер месяца - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"Год - Copy", type text}, {"Номер месяца - Copy", type text}}, "en-US"),{"Год - Copy", "Номер месяца - Copy"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"IndexMonth"),
    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns","-","-0",Replacer.ReplaceText,{"IndexMonth"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value","-012","-12",Replacer.ReplaceText,{"IndexMonth"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value3","-010","-10",Replacer.ReplaceText,{"IndexMonth"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","-011","-11",Replacer.ReplaceText,{"IndexMonth"}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Replaced Value2", "Год", "Год - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column3", "Номер недели", "Номер недели - Copy"),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column2", {{"Год - Copy", type text}, {"Номер недели - Copy", type text}}, "en-US"),{"Год - Copy", "Номер недели - Copy"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"IndexWeek"),
    #"Inserted End of Month" = Table.AddColumn(#"Merged Columns1", "EndOfMonth", each Date.EndOfMonth([Дата]), type date),
    #"Merged Columns2" = Table.CombineColumns(Table.TransformColumnTypes(#"Inserted End of Month", {{"StartOfWeek", type text}, {"EndOfWeek", type text}}, "ru-RU"),{"StartOfWeek", "EndOfWeek"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Неделя")
in
    #"Merged Columns2"
